// <auto-generated />
namespace verk5.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CommentAddedToLecture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentAddedToLecture));
        
        string IMigrationMetadata.Id
        {
            get { return "201304071252130_CommentAddedToLecture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
